### ISSUE TITLE
Studying the use of SuperTokens for UserAuthentication

### ISSUE THREAD

**Issue by Lamarcke** [coding-tree-io/appointmate#6]
I'm interested in learning what's the project goal, but i couldn't grasp much of it from the README, so i'm assuming this is the API for an Booking app (it is stated there, but i thought it was some sort of coding challenge from the checklists haha)

I want to recommend the use of SuperTokens to handle User Authentication. It handles most of the popular login flows (like social logins) and can issue JWTs.

The architecture would look like this:
- An API with the SuperTokens middleware (currently, it does not offer a Java SDK, so you would need to use a simple JS, Go or Python API)
- Front-end client communicates with said backend, and retrieves the JWT Token
- The Java API can verify the JWT as usual, except that it's important that both APIs share the same JWT secret

More info:
https://supertokens.com

**Comment by zantoichi** [comment]
Thanks for your interest in our project and your recommendation on using SuperTokens for user authentication. We'll consider it as we develop the project.

However, we're not accepting commits from outside contributors right now since we're still setting up the project. We appreciate your feedback on the README.
